name: CI

on: [push]

jobs:
  tests:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - run: go test mercure/*
